<?php
/**
 * Download ESP32 firmware (.ino) ที่ pre-fill WiFi credentials
 *
 * GET /api/firmware/esp32.php           → download ไฟล์ .ino
 * GET /api/firmware/esp32.php?preview=1 → ดู source บนหน้าเว็บ
 *
 * จะ replace:
 *   WIFI_SSID      → settings.wifi_ssid
 *   WIFI_PASSWORD  → settings.wifi_password
 *
 * เงื่อนไข: ต้อง login ก่อน (กัน leak WiFi password)
 */
require_once __DIR__ . '/../../includes/api_auth.php';

requireLogin();

$INO_PATH = realpath(__DIR__ . '/../../../esp32/door_controller/door_controller.ino');
if (!$INO_PATH || !is_file($INO_PATH)) {
    http_response_code(500);
    echo "ไม่พบไฟล์ firmware ต้นฉบับ: esp32/door_controller/door_controller.ino";
    exit;
}

try {
    $db = getDB();
    $rows = $db->query("SELECT setting_key, setting_value FROM settings WHERE setting_key IN ('wifi_ssid','wifi_password')")->fetchAll();
    $cfg = ['wifi_ssid' => '', 'wifi_password' => ''];
    foreach ($rows as $r) $cfg[$r['setting_key']] = $r['setting_value'];
} catch (Throwable $e) {
    http_response_code(500);
    echo "DB error: " . htmlspecialchars($e->getMessage());
    exit;
}

if ($cfg['wifi_ssid'] === '') {
    http_response_code(400);
    header('Content-Type: text/plain; charset=utf-8');
    echo "ยังไม่ได้ตั้ง WiFi SSID — เปิด /settings.php ไปตั้งค่า WiFi ก่อน\n";
    exit;
}

// Escape backslash + double quote สำหรับใส่ใน C string
function escape_c_string($s) {
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $s);
}

$src = file_get_contents($INO_PATH);

// แทนที่บรรทัด WIFI_SSID = "..."  และ  WIFI_PASSWORD = "..."
$src = preg_replace(
    '/const\s+char\*\s+WIFI_SSID\s*=\s*"[^"]*"\s*;/',
    'const char* WIFI_SSID            = "' . escape_c_string($cfg['wifi_ssid']) . '";',
    $src, 1
);
$src = preg_replace(
    '/const\s+char\*\s+WIFI_PASSWORD\s*=\s*"[^"]*"\s*;/',
    'const char* WIFI_PASSWORD        = "' . escape_c_string($cfg['wifi_password']) . '";',
    $src, 1
);

// Header signature ให้รู้ว่ามาจาก web
$signature = "// Generated by Bunny Door web at " . date('Y-m-d H:i:s')
           . " for WiFi: \"" . $cfg['wifi_ssid'] . "\"\n";
$src = $signature . $src;

if (!empty($_GET['preview'])) {
    header('Content-Type: text/plain; charset=utf-8');
    echo $src;
    exit;
}

// Download ไฟล์
$filename = 'door_controller.ino';
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($src));
header('X-Content-Type-Options: nosniff');
echo $src;
exit;
