<?php
/**
 * Download ESP32 firmware (.ino) ที่ pre-fill WiFi credentials
 *
 * GET /api/firmware/esp32.php           → download ไฟล์ .ino
 * GET /api/firmware/esp32.php?preview=1 → ดู source บนหน้าเว็บ
 *
 * จะ replace:
 *   WIFI_SSID      → settings.wifi_ssid
 *   WIFI_PASSWORD  → settings.wifi_password
 *
 * เงื่อนไข: ต้อง login ก่อน (กัน leak WiFi password)
 */
require_once __DIR__ . '/../../includes/api_auth.php';

requireLogin();

$INO_PATH = realpath(__DIR__ . '/../../../esp32/door_controller/door_controller.ino');
if (!$INO_PATH || !is_file($INO_PATH)) {
    http_response_code(500);
    echo "ไม่พบไฟล์ firmware ต้นฉบับ: esp32/door_controller/door_controller.ino";
    exit;
}

try {
    $db = getDB();
    $rows = $db->query("SELECT setting_key, setting_value FROM settings WHERE setting_key IN ('wifi_ssid','wifi_password')")->fetchAll();
    $cfg = ['wifi_ssid' => '', 'wifi_password' => ''];
    foreach ($rows as $r) $cfg[$r['setting_key']] = $r['setting_value'];
} catch (Throwable $e) {
    http_response_code(500);
    echo "DB error: " . htmlspecialchars($e->getMessage());
    exit;
}

// ── Auto-fetch จาก Pi ถ้า settings ว่าง ──
// (Pi รู้ WiFi ของตัวเองอยู่แล้ว — ไม่ต้องให้ user กรอกซ้ำ)
if ($cfg['wifi_ssid'] === '' || $cfg['wifi_password'] === '') {
    try {
        $ch = curl_init(FACE_SERVER_URL . '/api/wifi/current');
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 5,
            CURLOPT_CONNECTTIMEOUT => 3,
        ]);
        $resp = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($code === 200 && $resp) {
            $piWifi = json_decode($resp, true);
            if (is_array($piWifi)) {
                // อัปเดต settings เพื่อ cache ครั้งต่อไป (และเอาไป generate)
                if (empty($cfg['wifi_ssid']) && !empty($piWifi['ssid'])) {
                    $cfg['wifi_ssid'] = $piWifi['ssid'];
                    $u = $db->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('wifi_ssid', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
                    $u->execute([$piWifi['ssid']]);
                }
                if (empty($cfg['wifi_password']) && !empty($piWifi['password'])) {
                    $cfg['wifi_password'] = $piWifi['password'];
                    $u = $db->prepare("INSERT INTO settings (setting_key, setting_value) VALUES ('wifi_password', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
                    $u->execute([$piWifi['password']]);
                }
            }
        }
    } catch (Throwable $e) {
        // ไม่ critical — fall through ไปข้างล่าง
    }
}

if ($cfg['wifi_ssid'] === '') {
    http_response_code(400);
    header('Content-Type: text/plain; charset=utf-8');
    echo "ยังไม่ได้ตั้ง WiFi SSID\n";
    echo "ทางเลือก:\n";
    echo "  1. รอ Pi pair กับ web ก่อน (ระบบจะดึง WiFi จาก Pi อัตโนมัติ)\n";
    echo "  2. หรือเปิด /settings.php ไปตั้งค่า WiFi เองก่อน\n";
    exit;
}

// Escape backslash + double quote สำหรับใส่ใน C string
function escape_c_string($s) {
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $s);
}

$src = file_get_contents($INO_PATH);

// แทนที่บรรทัด WIFI_SSID = "..."  และ  WIFI_PASSWORD = "..."
$src = preg_replace(
    '/const\s+char\*\s+WIFI_SSID\s*=\s*"[^"]*"\s*;/',
    'const char* WIFI_SSID            = "' . escape_c_string($cfg['wifi_ssid']) . '";',
    $src, 1
);
$src = preg_replace(
    '/const\s+char\*\s+WIFI_PASSWORD\s*=\s*"[^"]*"\s*;/',
    'const char* WIFI_PASSWORD        = "' . escape_c_string($cfg['wifi_password']) . '";',
    $src, 1
);

// Header signature ให้รู้ว่ามาจาก web
$signature = "// Generated by Bunny Door web at " . date('Y-m-d H:i:s')
           . " for WiFi: \"" . $cfg['wifi_ssid'] . "\"\n";
$src = $signature . $src;

if (!empty($_GET['preview'])) {
    header('Content-Type: text/plain; charset=utf-8');
    echo $src;
    exit;
}

// Download ไฟล์
$filename = 'door_controller.ino';
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($src));
header('X-Content-Type-Options: nosniff');
echo $src;
exit;
